version: '3.8'

services:
  # 1. 백엔드 앱 서비스 (FastAPI)
  backend:
    build: .  # 현재 폴더의 Dockerfile을 사용해 이미지를 빌드
    container_name: photo_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # <-- 코드 변경 시 자동 재시작
    volumes:
      - ./app:/code/app  # <-- 중요: 로컬 app 폴더를 컨테이너 /code/app에 연결 (개발용)
    ports:
      - "8000:8000"      # 내 컴퓨터 8000번 포트 <-> 컨테이너 8000번 포트
    env_file:
      - ./.env           # .env 파일의 변수들을 컨테이너 환경변수로 주입
    depends_on:
      - db               # 'db' 서비스가 먼저 실행된 후 'backend'가 실행됨

  # 2. 데이터베이스 서비스 (PostgreSQL)
  db:
    image: postgres:15-alpine # 도커 허브에서 postgres 15버전 이미지 가져오기
    container_name: photo_db
    env_file:
      - ./.env           # .env 파일에서 POSTGRES_DB, USER, PASSWORD 가져오기
    volumes:
      - postgres_data:/var/lib/postgresql/data # <-- 중요: DB 데이터를 내 컴퓨터에 저장 (영속성)
    ports:
      - "5432:5432"      # (선택) DB툴로 내 컴퓨터에서 직접 접속할 때 사용
    restart: unless-stopped

volumes:
  # DB 데이터가 저장될 볼륨 정의
  postgres_data: